### ISSUE TITLE
Parse pre-quitesite and co-requisute data from course detail information

### ISSUE THREAD

**Issue by aomi** [VikeLabs/uvic-course-scraper#35]
# Problem
Currently, per-requisite and co-requisite information is stored under the `preAndCorequisites` key. An example file can be found [here](
https://uvic.kuali.co/api/v1/catalog/course/5eb09dad7a30f7001af74eb1/Byd_gu6QE). Since the information is stored as HTML inside JSON, it is not easily usable. Upon further analysis, the data is not consistently structured making parsing it difficult.
# Solution
Code a parse the HTML and output a structured object.

Likely you can access the data given `let c` be the course JSON info like from the example.
```
const $ = cheerio.load(c.preAndCorequisites);
```

```json
"preAndCorequisites":"<div><div><div><ul><li data-test=\"ruleView-A\"><div data-test=\"ruleView-A-result\">Complete <span>1</span> of: <div><ul style=\"margin-top:5px;margin-bottom:5px\"><li><span><a href=\"#/courses/view/5cbdf57867a5c324003b0c2c\" target=\"_blank\">ECE260</a> <!-- -->- <!-- -->Continuous-Time Signals and Systems<!-- --> <span style=\"margin-left:5px\">(1.5)</span></span></li><li><span><a href=\"#/courses/view/5c4ff2cdbb9b5e24008114ba\" target=\"_blank\">ELEC260</a> <!-- -->- <!-- -->Continuous-Time Signals and Systems<!-- --> <span style=\"margin-left:5px\">(1.5)</span></span></li></ul></div></div></li></ul></div></div></div>"
```
# Acceptance Criteria
The following is the acceptance criteria:
- The solution must be in Typescript and use the available libraries in the repository. One should not add any libraries unless the developer can prove otherwise the library is essential to the solution. 
- The solution must be able to work on 95% of all courses with a pre-requisite and co-requisite. Cases where these object keys are empty do not count towards the calculation of 95%. Note that this percentage is calculated per available calendar/semester.
- The solution must be able to prove that is it functional using tests and the provided test script.  
- The solution must output the pre/co-requisites in the following schema.
- The solution must pass the basic test suite provided otherwise the submission will not be considered.

**Comment by sfaigan** [comment]
oops sorry didn't know I had edit access!
