### ISSUE TITLE
Automate NPM package publishing

### ISSUE THREAD

**Issue by aomi** [VikeLabs/uvic-course-scraper#80]
As a developer, the process of publishing the package to npm should be mostly automated.
Prior to a merge into master, the following should happen:
1. The package version is updated according to semantic version principals either being automated, where the bump to the version is done automatically or the bump to the version is enforced by CI but done by the developer.
Ideally when a branch is merged into master the following should happen:
1. Publish to npm
2. Create a Git/GitHub release tag.

**Comment by aomi** [comment]
https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md

**Comment by isaaccormack** [comment]
closed by #92
