### ISSUE TITLE
Store Kuali links in a static file

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/uvic-course-scraper#85]
Kuali links are subject to change for different semesters. Obviously we don't want to be hitting old Kuali links as time goes on and we ideally don't want to leave it to developers to update the links every semester.

It would be nice if we had a function which runs periodically (i.e. at the beginning of a semester or when a new schedule comes out) that finds the link UVic is currently hitting, and puts it in a JSON file with the associated term.
To visualize this:
`
{
'202101': <insert kuali link here>,
'202109': <insert diff kuali link here>
}
`

_This can be implemented now, but needs to be monitored as it would be nice to know exactly when Kuali links change and stuff like that, which will take some time._

**Comment by aomi** [comment]
Trigger an action on a schedule:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
Execute a snapshot test =Profit?
