### ISSUE TITLE
getCourseDetails() throws error when course doesn't have hoursCatalogText 

### ISSUE THREAD

**Issue by isaaccormack** [VikeLabs/uvic-course-scraper#90]
This came up when testing during backend deployment. 

This bug can be reproduced by running UVicCourseScraper.getCourseDetails("Hkc3nP6XV").

**Comment by shergillmanav19** [comment]
sounds good will look into this

**Comment by isaaccormack** [comment]
This was actually just an error on my end when rewriting some stuff in feature/simplify-API, not Manav's fault.  

Fixed by #89
